name: npm build

on: [push]

env: 
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{github.repository}}

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - run: npm test -- --coverage
      - run: CI=false npm run build --if-present
      - name: Upload coverage reports
        run: COVERALLS_REPO_TOKEN="${{secrets.COVERALLS_TOKEN}}" npm run coveralls
  
  build_and_publish_image:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps: 
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1.14.1
        with: 
          registry: ${{env.REGISTRY}}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3.6.2
        with: 
          images: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}

      - name: build and push Docker image
        uses: docker/build-push-action@v3
        with: 
          context: .
          push: true
          tags: ghcr.io/omallassi/apis-catalog-web:master